//! T1 PROBE — THROWAWAY. The Golem-side half of the `probe-tool` builtin.
//!
//! Delete with `clank-core/src/builtins/probe.rs` once
//! `dev-docs/research/agent-tools-probes.md` is finished.
//!
//! Four things this file pins down for tickets 3 and 5:
//!
//! 1. **The bindings live in the ungated world.** `golem_rust::bindings::golem::tool::host` is
//!    available without `export_golem_agentic` — the same place `agent_invoker.rs` gets `WasmRpc`.
//!    The plan's sketch named `golem_rust::golem_agentic::golem::tool::host`, which is gated behind
//!    a feature only a leaf component may enable, so it would not have compiled here.
//! 2. **`block_on` must come from the SDK's own bindgen.** The futures returned by
//!    `invoke_and_await` are generated by the golemcloud wit-bindgen fork golem-rust pins, so they
//!    are driven by *that* crate's `block_on`, not the `wasip3` re-export the earlier spike used.
//! 3. **Discovery is a host import.** `get_all_tools` here returns the tools this agent is *bound
//!    to*. The SDK's `agentic::get_all_tools()` is a different function — a guest-side registry of
//!    the tools a component *implements* — which for clank is empty.
//! 4. **The canonical input record cannot be hand-authored.** Encoding a Rust struct that "looks
//!    like" the command's parameters is rejected with `InvalidInput("tool input schema does not
//!    match the selected command")`: the host compares the sent graph against
//!    `Tool::canonical_input_record_schema` with `is_equivalent_cross_graph`, and the record's
//!    field set, order and types all come from the tool's declaration — globals (options then
//!    flags) collected along the path root→command, then the body's fixed positionals, tail,
//!    options and flags. So this probe builds every input from the tool's OWN model, via
//!    `decode_tool` → `canonical_input_model`. That is the mechanism ticket 3's `encode_input` and
//!    ticket 5's projection must implement; a local mirror type is not a shortcut, it simply does
//!    not work.

// Throwaway probe: the coercion arms cast parsed u64s down to the declared width and the dumps
// build strings with `format!`. Ticket 3's real encoder gets checked conversions and a proper
// error type; this module is deleted when it lands, so the pedantic lints are silenced here rather
// than paid for twice.
#![allow(
    clippy::cast_possible_truncation,
    clippy::cast_sign_loss,
    clippy::format_push_string,
    clippy::missing_errors_doc
)]

use golem_rust::bindings::golem::tool::host as tool_host;
use golem_rust::schema::tool::wit::decode_tool;
use golem_rust::schema::{SchemaGraph, SchemaType, SchemaValue};

/// Build a command's canonical input record from `(canonical name, argument)` pairs, using the
/// tool's own declared model. Pairs are matched by name, so their order here is irrelevant — the
/// record is assembled in the model's order, which is the only order the host accepts.
fn encode_for(
    tool_name: &str,
    path: &[&str],
    args: &[(&str, String)],
) -> Result<golem_rust::schema::wit::wire::TypedSchemaValue, String> {
    let registered = tool_host::get_all_tools()
        .into_iter()
        .find(|t| {
            t.definition
                .commands
                .nodes
                .first()
                .is_some_and(|n| n.name == tool_name)
        })
        .ok_or_else(|| format!("tool '{tool_name}' is not bound to this agent"))?;
    let tool = decode_tool(registered.definition).map_err(|e| format!("decode_tool: {e:?}"))?;
    let owned: Vec<String> = path.iter().map(|s| (*s).to_string()).collect();
    let index = tool
        .command_index_by_path(&owned)
        .ok_or_else(|| format!("{tool_name}: no command at path {path:?}"))?;
    let model = tool
        .canonical_input_model(index)
        .map_err(|e| format!("canonical_input_model: {e:?}"))?;

    let mut fields = Vec::with_capacity(model.fields.len());
    for field in &model.fields {
        let supplied = args
            .iter()
            .find(|(name, _)| *name == field.name)
            .map(|(_, value)| value.as_str());
        fields.push(value_for(&model.record_schema, &field.type_, supplied)?);
    }
    let typed = golem_rust::TypedSchemaValue::new(
        model.record_schema.clone(),
        SchemaValue::Record { fields },
    );
    golem_rust::encode_typed_schema_value(&typed).map_err(|e| format!("encode: {e:?}"))
}

/// Ticket 5's coercion table in miniature: a command-line string against one declared type.
///
/// `graph` is the canonical record's own graph, needed because a field may be a `Ref` into its
/// defs — that is how a record-typed option (`tree add --meta`) arrives: the macro unwraps an
/// `Option<T>` parameter to `T` ("it only makes the argument not-required"), so the canonical
/// field type is the bare `Ref(Meta)`, and the record has to carry a `Meta` value.
fn value_for(
    graph: &SchemaGraph,
    ty: &SchemaType,
    supplied: Option<&str>,
) -> Result<SchemaValue, String> {
    let parse = |fallback: u64| -> u64 {
        supplied
            .and_then(|s| s.parse::<u64>().ok())
            .unwrap_or(fallback)
    };
    Ok(match ty {
        SchemaType::String { .. } => SchemaValue::String(supplied.unwrap_or_default().to_string()),
        SchemaType::Bool { .. } => {
            SchemaValue::Bool(matches!(supplied, Some("true" | "1" | "yes" | "on")))
        }
        SchemaType::U8 { .. } => SchemaValue::U8(parse(0) as u8),
        SchemaType::U16 { .. } => SchemaValue::U16(parse(0) as u16),
        SchemaType::U32 { .. } => SchemaValue::U32(parse(0) as u32),
        SchemaType::U64 { .. } => SchemaValue::U64(parse(0)),
        SchemaType::S32 { .. } => SchemaValue::S32(
            supplied
                .and_then(|s| s.parse::<i32>().ok())
                .unwrap_or_default(),
        ),
        SchemaType::S64 { .. } => SchemaValue::S64(
            supplied
                .and_then(|s| s.parse::<i64>().ok())
                .unwrap_or_default(),
        ),
        SchemaType::Option { inner, .. } => SchemaValue::Option {
            inner: match supplied.filter(|s| !s.is_empty()) {
                Some(text) => Some(Box::new(value_for(graph, inner, Some(text))?)),
                None => None,
            },
        },
        SchemaType::List { element, .. } => {
            let mut elements = Vec::new();
            if let Some(text) = supplied.filter(|s| !s.is_empty()) {
                for part in text.split(',') {
                    elements.push(value_for(graph, element, Some(part))?);
                }
            }
            SchemaValue::List { elements }
        }
        SchemaType::Map { key, value, .. } => {
            let mut entries = Vec::new();
            if let Some(text) = supplied.filter(|s| !s.is_empty()) {
                for part in text.split(',') {
                    let (k, v) = part
                        .split_once('=')
                        .ok_or_else(|| format!("map entry '{part}' is not k=v"))?;
                    entries.push((
                        value_for(graph, key, Some(k))?,
                        value_for(graph, value, Some(v))?,
                    ));
                }
            }
            SchemaValue::Map { entries }
        }
        // A named type: resolve through the record graph's defs and build its body.
        SchemaType::Ref { id, .. } => {
            let def = graph
                .defs
                .iter()
                .find(|def| &def.id == id)
                .ok_or_else(|| format!("dangling ref {id:?} in canonical record graph"))?;
            value_for(graph, &def.body, supplied)?
        }
        // A record-typed field: zero-valued members (the probe never spells a JSON literal).
        SchemaType::Record { fields, .. } => SchemaValue::Record {
            fields: fields
                .iter()
                .map(|field| value_for(graph, &field.body, None))
                .collect::<Result<Vec<_>, _>>()?,
        },
        other => return Err(format!("unsupported canonical field type: {other:?}")),
    })
}

/// One real `tool-rpc` call, run to completion from synchronous code.
///
/// When the command declares a stdout stream, the terminal wait and the stream drain are joined
/// inside the same `block_on` — the shape the nested-`block_on` spike did not exercise, and the one
/// every streaming tool needs.
fn call(
    tool: &str,
    path: &[&str],
    args: &[(&str, String)],
    want_stdout: bool,
) -> Result<(Vec<u8>, u8), String> {
    let input = encode_for(tool, path, args)?;
    let tool = tool.to_string();
    let path: Vec<String> = path.iter().map(|s| (*s).to_string()).collect();
    wit_bindgen::block_on(async move {
        let rpc = tool_host::ToolRpc::new(&tool);
        if want_stdout {
            let (target, reader) = tool_host::create_stdout();
            let invocation = rpc.invoke_and_await(path, input, None, Some(target));
            let drain = async move {
                let mut reader = reader;
                let mut out = Vec::new();
                while let Some(item) = reader.next().await {
                    match item {
                        Ok(chunk) => out.extend(chunk),
                        Err(failure) => return (out, Some(format!("{failure:?}"))),
                    }
                }
                (out, None)
            };
            let (result, (stdout, stream_failure)) = futures::join!(invocation, drain);
            if let Some(failure) = stream_failure {
                return Err(format!("stdout stream failed: {failure}"));
            }
            render(result, stdout)
        } else {
            let result = rpc.invoke_and_await(path, input, None, None).await;
            render(result, Vec::new())
        }
    })
}

/// The output rule ticket 6 will implement: the stream when one was declared, otherwise the
/// structured result. Never both.
fn render(
    result: Result<tool_host::InvocationResult, tool_host::RpcError>,
    stdout: Vec<u8>,
) -> Result<(Vec<u8>, u8), String> {
    match result {
        Ok(invocation) => {
            if stdout.is_empty() {
                let rendered = match invocation.result {
                    Some(value) => match plain_string(&value) {
                        Some(text) => format!("{text}\n"),
                        None => format!("{value:?}\n"),
                    },
                    None => String::new(),
                };
                Ok((rendered.into_bytes(), 0))
            } else {
                Ok((stdout, 0))
            }
        }
        // Exit-code mapping needs the tool's declared error cases, which is ticket 3's
        // `resolve_error_case`; the probe only records what the wire error looks like.
        Err(error) => Err(format!("rpc error: {error:?}")),
    }
}

/// A result that is just a string, as plain text. Anything richer needs the projection's
/// formatter handling (ticket 5/6), so it falls back to a dump here.
fn plain_string(value: &golem_rust::schema::wit::wire::TypedSchemaValue) -> Option<String> {
    use golem_rust::schema::wit::wire::SchemaValueNode;
    let root = usize::try_from(value.value.root).ok()?;
    match value.value.value_nodes.get(root)? {
        SchemaValueNode::StringValue(text) => Some(text.clone()),
        _ => None,
    }
}

/// The command tree of every bound tool, and — for one command — the canonical input record the
/// host will demand. This is the metadata the projection consumes.
fn describe(tool_name: &str, path: &[&str]) -> Result<(Vec<u8>, u8), String> {
    let registered = tool_host::get_all_tools()
        .into_iter()
        .find(|t| {
            t.definition
                .commands
                .nodes
                .first()
                .is_some_and(|n| n.name == tool_name)
        })
        .ok_or_else(|| format!("tool '{tool_name}' is not bound to this agent"))?;
    let tool = decode_tool(registered.definition).map_err(|e| format!("decode_tool: {e:?}"))?;
    let owned: Vec<String> = path.iter().map(|s| (*s).to_string()).collect();
    let index = tool
        .command_index_by_path(&owned)
        .ok_or_else(|| format!("{tool_name}: no command at path {path:?}"))?;
    let model = tool
        .canonical_input_model(index)
        .map_err(|e| format!("canonical_input_model: {e:?}"))?;
    let mut out = format!("{tool_name} {}\ncanonical input record:\n", path.join(" "));
    for (position, field) in model.fields.iter().enumerate() {
        out.push_str(&format!(
            "  {}. {} : {}\n",
            position + 1,
            field.name,
            type_name(&field.type_)
        ));
    }
    Ok((out.into_bytes(), 0))
}

fn type_name(ty: &SchemaType) -> &'static str {
    match ty {
        SchemaType::String { .. } => "string",
        SchemaType::Bool { .. } => "bool",
        SchemaType::U32 { .. } => "u32",
        SchemaType::U64 { .. } => "u64",
        SchemaType::S64 { .. } => "s64",
        SchemaType::Option { .. } => "option",
        SchemaType::List { .. } => "list",
        SchemaType::Map { .. } => "map",
        SchemaType::Record { .. } => "record",
        SchemaType::Ref { .. } => "ref",
        _ => "other",
    }
}

thread_local! {
    /// The `state` the last `probe-tool bash` call returned, handed back on the next one — the
    /// caller-carried session, held here the way an interactive client would hold it.
    static BASH_STATE: std::cell::RefCell<String> = const { std::cell::RefCell::new(String::new()) };
}

/// SPIKE — one call to the bound `bash` tool (`bash run --state <last> <script>`).
///
/// The tool's result record is `{stdout, stderr, exit_code, pending_prompt, cwd, state}`. Its
/// stdout is written as-is, then its stderr lines prefixed `[bash stderr] `, then one trailer
/// `[bash exit=N cwd=… state=NB]`; the builtin exits with the tool's exit code.
fn call_bash(script: &str) -> Result<(Vec<u8>, u8), String> {
    let state = BASH_STATE.with(|s| s.borrow().clone());
    let input = encode_for(
        "bash",
        &["run"],
        &[("state", state), ("script", script.to_string())],
    )?;
    let result = wit_bindgen::block_on(async move {
        tool_host::ToolRpc::new("bash")
            .invoke_and_await(vec!["run".to_string()], input, None, None)
            .await
    });
    let invocation = result.map_err(|e| format!("rpc error: {e:?}"))?;
    let wire = invocation
        .result
        .ok_or_else(|| "bash returned no result".to_string())?;
    let typed =
        golem_rust::decode_typed_schema_value(&wire).map_err(|e| format!("decode: {e:?}"))?;
    let SchemaValue::Record { fields } = typed.value() else {
        return Err(format!("bash result is not a record: {:?}", typed.value()));
    };
    let text = |i: usize| match fields.get(i) {
        Some(SchemaValue::String(s)) => s.clone(),
        _ => String::new(),
    };
    let exit_code = match fields.get(2) {
        Some(SchemaValue::U8(code)) => *code,
        _ => 1,
    };
    let (stdout, stderr, cwd, new_state) = (text(0), text(1), text(4), text(5));
    BASH_STATE.with(|s| s.borrow_mut().clone_from(&new_state));
    let mut out = stdout;
    for line in stderr.lines() {
        out.push_str(&format!("[bash stderr] {line}\n"));
    }
    out.push_str(&format!(
        "[bash exit={exit_code} cwd={cwd} state={}B]\n",
        new_state.len()
    ));
    Ok((out.into_bytes(), exit_code))
}

/// Dispatch for the `probe-tool` builtin's argv.
pub fn run(argv: &[String]) -> Result<(Vec<u8>, u8), String> {
    let arg = |i: usize| argv.get(i).cloned().unwrap_or_default();
    let flag = |name: &str| argv.iter().any(|a| a == name).to_string();
    match argv[0].as_str() {
        // --- the minimal probe tools -------------------------------------------------------
        "no-stream" => call("probe", &["no-stream"], &[("value", arg(1))], false),
        "produce" => call(
            "probe",
            &["produce"],
            &[("count", arg(1)), ("text", arg(2))],
            true,
        ),
        "fail" => call("probe", &["fail"], &[("usage", flag("--usage"))], false),
        "capable" => call(
            "capable-probe",
            &["write-tag"],
            &[("path", arg(1)), ("text", arg(2)), ("tag", arg(3))],
            false,
        ),

        // --- the echo-tool fixture ---------------------------------------------------------
        "greet" => call(
            "echo-tool",
            &["greet"],
            &[
                ("name", arg(1)),
                (
                    "times",
                    if arg(2).is_empty() {
                        "1".into()
                    } else {
                        arg(2)
                    },
                ),
                ("shout", flag("--shout")),
                ("color", "auto".to_string()),
                ("verbose", "0".to_string()),
            ],
            false,
        ),
        "list" => call("echo-tool", &["list"], &[], false),
        "destroy" => call("echo-tool", &["destroy"], &[], false),
        "echo-fail" => call("echo-tool", &["fail"], &[("usage", flag("--usage"))], false),
        // Two-segment path: the parent forwards to the subtree child in-process.
        "tree-add" => call(
            "echo-tool",
            &["tree", "add"],
            &[("entries", format!("{}={}", arg(1), arg(2)))],
            false,
        ),

        // The fixture's filesystem-capable tool.
        "cwrite" => call(
            "capable-echo",
            &["write"],
            &[("path", arg(1)), ("text", arg(2))],
            false,
        ),
        "cread" => call("capable-echo", &["read"], &[("path", arg(1))], false),

        // --- SPIKE: the `bash` tool, state carried between calls by this agent ----------------
        "bash" => call_bash(&argv[1..].join(" ")),
        "bash-reset" => {
            BASH_STATE.with(|s| s.borrow_mut().clear());
            Ok((Vec::new(), 0))
        }
        "bash-state" => Ok((
            format!("{}\n", BASH_STATE.with(|s| s.borrow().len())).into_bytes(),
            0,
        )),

        // --- introspection ------------------------------------------------------------------
        "expect" => {
            let path: Vec<&str> = argv[2..].iter().map(String::as_str).collect();
            describe(&arg(1), &path)
        }
        "tools" => {
            let mut out = String::new();
            for registered in tool_host::get_all_tools() {
                let nodes = &registered.definition.commands.nodes;
                let root = &nodes[0];
                out.push_str(&format!(
                    "{} v{}\n",
                    root.name, registered.definition.version
                ));
                for index in &root.subcommands {
                    let child = &nodes[*index as usize];
                    let kids: Vec<&str> = child
                        .subcommands
                        .iter()
                        .map(|i| nodes[*i as usize].name.as_str())
                        .collect();
                    let suffix = if kids.is_empty() {
                        String::new()
                    } else {
                        format!(" -> [{}]", kids.join(", "))
                    };
                    out.push_str(&format!("  {}{}\n", child.name, suffix));
                }
            }
            Ok((out.into_bytes(), 0))
        }
        "meta" => Ok((
            format!("{:#?}\n", tool_host::get_all_tools()).into_bytes(),
            0,
        )),
        other => Err(format!("unknown subcommand '{other}'")),
    }
}
